# Copyright (c) 2021 Nordic Semiconductor ASA
# SPDX-License-Identifier: Apache-2.0

manifest:
  self:
    path: bldc_foc

  remotes:
    - name: zephyrproject-rtos-fork
      url-base: https://github.com/ASethi77

  projects:
    - name: zephyr
      remote: zephyrproject-rtos-fork
      revision: infineon_tle9879_ek_soc
      import: true
